version: "3"

services:
  bitcoind:
    restart: unless-stopped
    image: nicolasdorier/docker-bitcoin:0.17.0
    environment:
      BITCOIN_NETWORK: "${PINETREESHOP_NETWORK:-regtest}"
      BITCOIN_EXTRA_ARGS: |
        rpcuser=0I5rfLbJEXsg
        rpcpassword=yJt7h7D8JpQy
        server=1
        port="${PINETREESHOP_BITCOIND_PORT:-18444}"
        rpcport="${PINETREESHOP_BITCOIND_RPCPORT:-18443}"
        whitelist=0.0.0.0/0
        zmqpubrawblock=tcp://0.0.0.0:28332
        zmqpubrawtx=tcp://0.0.0.0:28333
    ports:
      - "${PINETREESHOP_BITCOIND_PORT:-18444}:${PINETREESHOP_BITCOIND_PORT:-18444}"
      - "${PINETREESHOP_BITCOIND_RPCPORT:-18443}:${PINETREESHOP_BITCOIND_RPCPORT:-18443}"
    expose:
      - "${PINETREESHOP_BITCOIND_PORT:-18444}"
      - "${PINETREESHOP_BITCOIND_RPCPORT:-18443}"
    volumes:
      - "./bitcoind_dir:/home/bitcoin/.bitcoin"
  lnd:
    restart: unless-stopped
    image: btcpayserver/lnd:v0.5.1-beta-2
    environment:
      LND_CHAIN: "btc"
      LND_ENVIRONMENT: "${PINETREESHOP_NETWORK:-regtest}"
      LND_EXTRA_ARGS: |
        restlisten=0.0.0.0:8080
        bitcoin.node=bitcoind
        bitcoind.rpchost=bitcoind:${PINETREESHOP_BITCOIND_RPCPORT:-18443}
        bitcoind.rpcuser=0I5rfLbJEXsg
        bitcoind.rpcpass=yJt7h7D8JpQy
        bitcoind.zmqpubrawblock=tcp://bitcoind:28332
        bitcoind.zmqpubrawtx=tcp://bitcoind:28333
        trickledelay=1000
        externalip=lnd_for_balancer:9735
        no-macaroons=1
        debuglevel=debug
        noseedbackup=1
    ports:
      - "${PINETREESHOP_LND_RESTPORT:-23872}:8080"
    expose:
      - "23872"
      - "9735"
      - "8080"
    volumes:
      - "./lnd_dir:/data"
      - "./bitcoind_dir:/deps/.bitcoin"
    links:
      - bitcoind
  postgresql:
    restart: unless-stopped
    image: postgres:10.5
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    user: root

  pgadmin4:
    restart: unless-stopped
    image: dpage/pgadmin4:3.3
    container_name: pgadmin4
    command: -s --bind=0.0.0.0 --listen=80  --url postgresql://test:@postgres/test?sslmode=disable
    links:
      - postgresql:postgresql
    ports:
      - 80:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
